version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: leader
      POSTGRES_DB: leader
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  leader:
    build: 
      context: leader
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:leader@leader:5432
  chunk_server:
    build:
      context: chunk-server
      dockerfile: Dockerfile
    environment:
      - SERVER_ID=${SERVER_ID}
    volumes:
      - chunk_storage:/app/chunk_storage
      - ./chunk_metadata.db:/app/chunk_metadata.db
    ports:
      - "8001:8000"

volumes:
  postgres_data:
